site_name: vchord_bm25 v0.3.0

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - md_in_html

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

repo_url: https://github.com/pgEdge/postgresql-docs

nav:
  - vchord_bm25 v0.3.0: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - More Examples: more-examples.md
  - Tokenizer: tokenizer.md
  - Tokenizer Options: tokenizer-options.md
  - Installation: installation.md
  - Comparison to other solution in Postgres: comparison-to-other-solution-in-postgres.md
  - Limitation: limitation.md
  - Reference: reference.md
  - License: license.md
