site_name: psycopg2 dev

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

repo_url: https://github.com/pgEdge/postgresql-docs

nav:
  - Home: index.md
  - Installation: install.md
  - Basic module usage: usage.md
  - The psycopg2 module content: module.md
  - The connection class: connection.md
  - The cursor class: cursor.md
  - More advanced topics: advanced.md
  - psycopg2.extensions -- Extensions to the DB API: extensions.md
  - psycopg2.extras -- Miscellaneous goodies for Psycopg 2: extras.md
  - psycopg2.errors -- Exception classes mapping PostgreSQL errors: errors.md
  - psycopg2.sql -- SQL string composition: sql.md
  - psycopg2.tz --  tzinfo implementations for Psycopg 2: tz.md
  - psycopg2.pool -- Connections pooling: pool.md
  - psycopg2.errorcodes -- Error codes defined by PostgreSQL: errorcodes.md
  - Frequently Asked Questions: faq.md
  - Release notes: news.md
  - License: license.md
